name: 'MAJESTY '
favicon: null
layout_spectrum: 0.4854087352287024
typography_spectrum: 0.08805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#69758b'
    - '#a6a2a3'
    - '#1e2225'
    - '#fefefe'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
