name: 'MAJESTY '
favicon: null
layout_spectrum: 0.4854087352287024
typography_spectrum: 0.9172605362255126
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e0d3c6'
    - '#b5a08f'
    - '#302720'
    - '#584e40'
  brandStrength: 0.125
  lightness: 0.7443781481124461
  saturation: 0.5
  rhythmicContrast: 0.7897976255044341
purpose: []
